// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pad_data`

Future<String> desEncrypt({required List<int> data, required List<int> key}) =>
    RustLib.instance.api.crateApiDesDesEncrypt(data: data, key: key);

Future<Uint8List> desDecrypt(
        {required String encryptedBase64, required List<int> key}) =>
    RustLib.instance.api
        .crateApiDesDesDecrypt(encryptedBase64: encryptedBase64, key: key);
